# Generated by Django 4.0 on 2021-12-15 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='product name')),
                ('publisher_name', models.CharField(max_length=200, verbose_name='publisher name')),
                ('rent_status', models.BooleanField(default=False)),
                ('last_rented', models.DateTimeField(default=datetime.time(16, 0), verbose_name='last rented')),
            ],
        ),
    ]
