# Generated by Django 4.0 on 2021-12-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='last_rented',
            field=models.DateTimeField(auto_now_add=True, verbose_name='last rented'),
        ),
    ]
